version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_NAME: mydatabase
    ports:
      - "3001:3000"

volumes:
  pgdata:
